Repository coreruleset/modsecurity-docker, pull requests merged in 2022-09, with the labels that each got.

#139 chore: update modsecurity release
  README.md
  docker-bake.hcl
  v2-apache/Dockerfile
  v2-apache/Dockerfile-alpine
  v3-nginx/Dockerfile
  v3-nginx/Dockerfile-alpine
Labels: cve

#140 feat(ci): use unique tags when pushing to hub
  .github/workflows/dockerimage.yml
  .github/workflows/verifyimage.yml
  README.md
  docker-bake.hcl
  v3-nginx/Dockerfile
Labels: enhancement

#145 bugfix: clean up log formats
  v2-apache/conf/extra/httpd-modsecurity.conf
  v3-nginx/templates/conf.d/logging.conf.template
Labels: bug
